### ISSUE TITLE
Class not found

### ISSUE THREAD

**Issue by miguelsmuller** [pacuna/Laravel-PGSchema#11]
I'm using laravel 5.2.
I did the installation as documentation but I can not make the component work.

I'm getting the error: Class 'App \ Repositories \ PGSchema' not found

**Comment by miguelsmuller** [comment]
Someone ?

**Comment by pacuna** [comment]
hi @miguelsmuller , this package hasn't been tested with the 5.2 version yet. I'll try to make som time to check this. Thanks for the report.

**Comment by gjunior-tray** [comment]
hi @miguelsmuller,

try call **\PGSchema**  with **\** in the repository class...
